# Generated by Django 3.1.4 on 2020-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtQuestion',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='doubt/images')),
            ],
        ),
    ]
