# Generated by Django 3.1.4 on 2020-12-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubtquestion',
            name='image',
        ),
    ]
