# Generated by Django 3.1.4 on 2020-12-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0002_remove_doubtquestion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
